version: '3.9'
services:
     web: 
        container_name: course_container
        build: .
        command: >
              bash -c "python manage.py makemigrations
              && python manage.py migrate
              && python manage.py runserver 0.0.0.0:8000"
        volumes:
          - .:/course
        ports:
          - 10666:8000
        depends_on:
          - db
     
     db:
        image: postgres
        container_name: db_course
        environment:
          - POSTGRES_DB=coursedb
          - POSTGRES_USER=test2
          - POSTGRES_PASSWORD=password
          - POSGRES_HOST_AUTH_METHOD=trust
        volumes:
          - pgdata:/var/lib/postgress/data
volumes:
      pgdata: 



