# Generated by Django 4.0.5 on 2022-06-10 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
